# Generated by Django 3.0.7 on 2021-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='costcoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
